//! Wire protocol between crawler-server and crawler-node.
//!
//! The node is deliberately ignorant of crawl semantics: the entire surface
//! is "here are opaque rate-limited Riot GETs to run" and "here is what came
//! back". Server-side strategy can change arbitrarily without touching this.
//!
//! Compatibility rules: additive changes only (new optional fields with
//! `#[serde(default)]`), unknown fields are ignored by serde by default.
//! Bump [`PROTOCOL_VERSION`] only for breaking changes; the server rejects
//! mismatched versions with 426 and a human-readable message the node
//! prints verbatim.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

pub const PROTOCOL_VERSION: u32 = 1;
/// Every request carries this header with [`PROTOCOL_VERSION`] as value.
pub const PROTO_HEADER: &str = "x-crawler-proto";

// ---- enrollment ----

#[derive(Debug, Serialize, Deserialize)]
pub struct EnrollRequest {
    /// One-time invite code generated by `crawler-server invite`.
    pub invite_code: String,
    /// Node name, unique per server, `[a-z0-9_-]{1,32}`.
    pub name: String,
    #[serde(default)]
    pub client_version: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct EnrollResponse {
    /// Bearer token for all subsequent requests. Shown once; the node
    /// stores it locally, the server only keeps a hash.
    pub token: String,
    pub name: String,
}

// ---- work ----

#[derive(Debug, Serialize, Deserialize)]
pub struct WorkRequest {
    /// Jobs the node already holds (queued + running) per routing host.
    /// The server tops each host up to its per-node inflight target, so the
    /// node never needs to know which hosts exist.
    #[serde(default)]
    pub pending: HashMap<String, u32>,
    /// Long-poll budget: the server holds the request up to this long when
    /// it has nothing to hand out (capped server-side).
    #[serde(default)]
    pub wait_ms: u64,
    #[serde(default)]
    pub client_version: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct WorkResponse {
    #[serde(default)]
    pub jobs: Vec<Job>,
}

/// One opaque Riot API GET. `host` is the routing host prefix
/// (`europe`, `euw1`, ...): the node requests
/// `https://{host}.api.riotgames.com{path}` with its own key, applying its
/// own app limiter per host and method limiter per (host, method).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Job {
    pub id: u64,
    pub host: String,
    /// Method-limiter bucket, e.g. "match-v5.match".
    pub method: String,
    pub path: String,
    /// Lease: report the result within this window or the job is re-issued
    /// to another node.
    pub lease_ms: u64,
}

// ---- results ----

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum JobOutcome {
    /// 2xx; `body` is the response body.
    Ok,
    /// Definitive 404.
    NotFound,
    /// Riot rejected the node's API key (401/403) — the node pauses until
    /// its key is updated; the server re-issues the job elsewhere.
    KeyRejected,
    /// Gave up after retries (network / 5xx / unexpected status).
    Failed,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct JobResult {
    pub id: u64,
    pub outcome: JobOutcome,
    #[serde(default)]
    pub body: Option<String>,
    #[serde(default)]
    pub error: Option<String>,
}

/// Body of any non-2xx server response worth showing to the user
/// (e.g. 426 protocol mismatch, 403 bad invite).
#[derive(Debug, Serialize, Deserialize)]
pub struct ErrorResponse {
    pub message: String,
}
